import { TablePreset } from "./tableTypes";

export const modernTablePreset: TablePreset = {
  id: "table_modern",
  name: "Moderne",
  description: "En-tête bleu foncé, cellules Calibri 11, bordures fines grises, lignes alternées.",
  isBuiltIn: true,
  headerEnabled: true,
  header: {
    fontName: "Calibri",
    fontSize: 11,
    color: "#FFFFFF",
    bold: true,
    italic: false,
    horizontalAlignment: "center",
    verticalAlignment: "center",
    shadingColor: "#2B579A",
    spaceBefore: 4,
    spaceAfter: 4,
  },
  cells: {
    fontName: "Calibri",
    fontSize: 11,
    color: "#333333",
    bold: false,
    italic: false,
    horizontalAlignment: "left",
    verticalAlignment: "center",
    shadingColor: "",
    spaceBefore: 2,
    spaceAfter: 2,
  },
  bandedRows: true,
  bandedShadingColor: "#F2F2F2",
  borders: {
    outside: { style: "single", width: 1, color: "#BFBFBF" },
    inside: { style: "single", width: 0.5, color: "#D9D9D9" },
  },
  cellBullets: {
    fontName: "Calibri",
    fontSize: 10,
    color: "#333333",
    bold: false,
    italic: false,
    spaceBefore: 0,
    spaceAfter: 2,
    leftIndent: 12,
  },
};

export const academicTablePreset: TablePreset = {
  id: "table_academic",
  name: "Académique",
  description: "En-tête noir simple, Times New Roman 12, bordures noires uniformes.",
  isBuiltIn: true,
  headerEnabled: true,
  header: {
    fontName: "Times New Roman",
    fontSize: 12,
    color: "#000000",
    bold: true,
    italic: false,
    horizontalAlignment: "center",
    verticalAlignment: "center",
    shadingColor: "#EDEDED",
    spaceBefore: 4,
    spaceAfter: 4,
  },
  cells: {
    fontName: "Times New Roman",
    fontSize: 12,
    color: "#000000",
    bold: false,
    italic: false,
    horizontalAlignment: "left",
    verticalAlignment: "center",
    shadingColor: "",
    spaceBefore: 2,
    spaceAfter: 2,
  },
  bandedRows: false,
  bandedShadingColor: "#F5F5F5",
  borders: {
    outside: { style: "single", width: 1, color: "#000000" },
    inside: { style: "single", width: 0.5, color: "#000000" },
  },
  cellBullets: null,
};

export const builtInTablePresets: TablePreset[] = [modernTablePreset, academicTablePreset];
